name =input(" write the string here: ")
num =int(input(" write the int here: "))
num2 =float(input(" write the float here: "))
word =bool(input(" write the bool here: "))
print(name,num,num2,word)
print(type(name))
print(type(num))
print(type(num2))
print(type(word))